name: Build

on:
  workflow_dispatch:
    inputs:
      url:
        description: URL to download ISO from
        required: true
        type: string

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libarchive-tools squashfs-tools-ng wget

      - name: Download ISO
        run: wget ${{ inputs.url }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Build and Push task
        run: task push
